# Generated by Django 5.1 on 2024-09-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_or_ordered',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
