# Generated by Django 5.1 on 2024-09-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cartitem_cart_or_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user_email',
            field=models.EmailField(default='testuser@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_or_ordered',
            field=models.CharField(choices=[('C', 'Cart'), ('O', 'Ordered')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
